use super::KnownAcpRuntime;

pub(super) const CURSOR_RUNTIME: KnownAcpRuntime = KnownAcpRuntime {
    id: "cursor",
    label: "Cursor",
    commands: &["buzz-cursor-acp"],
    aliases: &["cursor-agent"],
    avatar_url: "",
    mcp_command: None,
    mcp_hooks: false,
    underlying_cli: Some("cursor-agent"),
    cli_install_commands: &["curl https://cursor.com/install -fsS | bash"],
    cli_install_commands_windows: &[],
    adapter_install_commands: &[],
    cli_install_instructions_url: "https://docs.cursor.com/en/cli/installation",
    adapter_install_instructions_url: "https://github.com/P0GL0L/buzz",
    cli_install_hint: "Buzz uses Cursor's official account-backed Agent CLI. Sign in once with `cursor-agent login`; credentials remain in Cursor-owned local storage.",
    adapter_install_hint: "The bounded Cursor ACP adapter ships with ASV Buzz.",
    skill_dir: Some(".cursor/skills"),
    supports_acp_model_switching: true,
    model_env_var: Some("BUZZ_CURSOR_MODEL"),
    provider_env_var: None,
    provider_locked: true,
    default_env: &[],
    config_file_path: None,
    config_file_format: None,
    supports_acp_native_config: false,
    thinking_env_var: None,
    max_tokens_env_var: None,
    context_limit_env_var: None,
    required_normalized_fields: &[],
    login_hint: Some("Run `cursor-agent login` to connect the Cursor account used by this Mac."),
    auth_probe_args: Some(&["cursor-agent", "status"]),
};
